== Contributors

The ksoap2-android has received contributions from individuals and companies. The source 
code repository includes a https://github.com/simpligility/ksoap2-android/graphs/contributors[list of contributor].

These contributions are managed by Manfred Moser from simpligility.

The following companies provide support for core contributors:

* http://www.simpligility.com/[simpligility] - core maintenance since Oct 2010

Other contributions have been sponsored by

* easywsdl

Please let us know if we have omitted you!

=== History

Long ago there was the ksoap and then the ksoap2 projects. After a successful 
phase SOAP and with it the library pretty much died. (at least there were no 
release since 2006 or so)

Android then revived that since a lightweight framework to talk to legacy SOAP 
services was needed.

A patch set for Android emerged on the "Android Developers" Google group 
authored by Jorge Jimenez.

Karl Michael Davis then took this patchset, set up a proper Apache Maven build 
as well as this project and did a few releases.

Since the project was largely unmaintained in 2009/2010 Manfred Moser from simpligility technologies inc. took over the project, updated the wiki, created 
a mailinglist, applied and created further patches and released 2.5.1 and has 
been cutting numerous releases with a number of enhancements since then.