== License Information

Ksoap2-android itself is licensed under an MIT license. It depends on other 
libraries licensed under different licenses.

Some source files include different licensing information in the header. In each
case, they appear to be Apache and BSD licenses. If this is a concern, use care
to examine the licenses and ensure they are compatible with your project.

=== Details

* Ksoap2-android, MIT, https://github.com/mosabua/ksoap2-android
* kxml2, permissive license, https://github.com/mosabua/kxml2
* kobjects, permissive license, https://github.com/mosabua/kobjects
* xmlpull, public domain, https://github.com/mosabua/xmlpull

=== Commercial Usage

It is the understanding of the current maintainers and committers that the 
licenses allow inclusion in proprietary application without a viral effect on 
the code of the application. We have not heard anything to the contrary from 
anyone, however we are not lawyers.

=== Credit

We would appreciate a credit in the application and a notification that you 
are using the library. It would also be great if you allow us to link to your application as a show case example.